spring:
  application:
    name: cloudgateway

  cloud:
    gateway:
      routes:
        - id: helloservice-route
          uri: http://localhost:8071
          predicates:
            - Path=/helloservice/**
            
        - id: factservice-route
          uri: http://localhost:8073
          predicates:
           - Path=/factorial/api1.0/**
           

server:
  port: 8072
